### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by JulienChavee** [Jujuwar/tfe_ftmanager#13]
- [ ] Vérifier les boutons des modales attendant un retour ajax et désactiver les boutons pendant le traitement
- [ ] Vérifier le cas où un match de barrage doit être généré (-> une des équipes de certains matchs est null)
- [ ] Tester chaque modale après avoir ajouter tous les null (voir #14)
